octomap:
  ros__parameters:
    sensor_model:
      hit: 0.7
      miss: 0.40
      max: 0.97
      min: 0.12

    dynamic_clearing:
      enabled: true
      free_observation_threshold: 2
      stale_time: 3.0
      stable_hit_threshold: 4
      stable_free_observation_threshold: 6
      force_free_updates: 4
